version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint_and_test:
    docker:
      - image: hub.c.163.com/kubediag/kubediag-dashboard-frontend:latest
    steps:
      - checkout
      - run:
          name: Lint code
          command: |
            npm lint
      - run:
          name: Run unit tests
          command: |
            npm test


# Orchestrate our job run sequence
workflows:
  lint_and_test:
    jobs:
      - lint_and_test

